#!/bin/bash
set -euo pipefail

TMPDIR=/tmp/pdfs
RESULT_DIR=/tmp/result

infile="$1"
base="${infile%.*}"
outfile="${base}.pdf"

log() { echo "$@" 2>&1; }

mkdir -p $TMPDIR $RESULT_DIR

log "infile=$1"
pdflatex -halt-on-error -output-directory=$TMPDIR $infile > "${RESULT_DIR}/${base}.log"
success=$?
mv "${TMPDIR}/${outfile}" "/${RESULT_DIR}/${outfile}"

ls "${RESULT_DIR}"

if [[ $success == 0 ]]; then
  cp "${RESULT_DIR}/${outfile}" .
  log "wrote ${outfile}"
fi
